# Generated by Django 4.2.9 on 2024-01-23 08:18

from django.db import migrations, models
import paste_bin.paste.models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_content_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(default=paste_bin.paste.models.generate_slug, max_length=8, unique=True),
        ),
    ]
