# Generated by Django 4.2.9 on 2024-02-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_content_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='text_format',
            field=models.CharField(choices=[('python', 'Python'), ('html', 'HTML'), ('javascript', 'Javascript'), ('css', 'CSS'), ('c', 'C'), ('c++', 'C++'), ('csharp', 'CSharp'), ('sql', 'SQL'), ('php', 'PHP'), ('bash', 'Bash')], max_length=10, null=True),
        ),
    ]
